#ifndef TURRET_STATE__COMMAND_MESSSAGE__H
#define TURRET_STATE__COMMAND_MESSAGE__H

enum class CommandResult {
    COMPLETED,
    CANCELED_BY_MCU,
    CANCELED_BY_REQUEST,
    ERROR
};

#endif //TURRET_STATE__COMMAND_MESSAGE__H