
#ifndef TURRET_CONFIG__ELEVATION_CONFIG_H
#define TURRET_CONFIG__ELEVATION_CONFIG_H

#define ELEVATION_MAX 740
#define ELEVATION_MIN 325
#define ELEVATION_RESOLUTION 15

#define MOTOR_MIN_SPEED 50
#define MOTOR_MED_SPEED 100
#define MOTOR_MAX_SPEED 150
#define MOTOR_JERK_SPEED 255
#define ELEV_JERK_LENGTH 10
#define MOTOR_UPDATE_INTERVAL 60

#endif // TURRET_CONFIG__ELEVATION_CONFIG_H
