
#ifndef TURRET_CONFIG__INDICATOR_CONFIG_H
#define TURRET_CONFIG__INDICATOR_CONFIG_H

#define ARD_STATUS_GRN 24
#define ARD_STATUS_RED 25

#define ACTY_LED_1 27
#define ACTY_LED_2 29
#define ACTY_LED_3 31

#define MOVE_LED_GRN 50
#define MOVE_LED_RED 51
#define MOVE_LED_BLUE 53

#define CANNON_LED 52

#endif // TURRET_CONFIG__INDICATOR_CONFIG_H