
#ifndef TURRET_CONFIG__INDICATOR_CONFIG_H
#define TURRET_CONFIG__INDICATOR_CONFIG_H

#define ALERT_BLINK_TIMES 6

#define BLINK_FAST_DELAY 270
#define BLINK_MED_DELAY 360
#define BLINK_SLOW_DELAY 450

#define STROBE_FAST_DELAY 60
#define STROBE_MED_DELAY 90
#define STROBE_SLOW_DELAY 120

#endif // TURRET_CONFIG__INDICATOR_CONFIG_H