
#ifndef TURRET_CONFIG__IR_CONFIG_H
#define TURRET_CONFIG__IR_CONFIG_H

#define IR_TRIGGER 2

#define IR_SENSOR_HIT 26
#define IR_SENSOR_DIRECTION_1 28
#define IR_SENSOR_DIRECTION_2 30
#define IR_SENSOR_DIRECTION_3 32
#define IR_SENSOR_DIRECTION_4 34

#endif // TURRET_CONFIG__IR_CONFIG_H