
#ifndef TURRET_CONFIG__TRAVERSE_CONFIG_H
#define TURRET_CONFIG__TRAVERSE_CONFIG_H

#define TRAVERSE_LIMIT_MIN 20
#define TRAVERSE_LIMIT_MAX 170
#define TRAVERSE_LIMIT_STRAIGHT 100

#define TRAVERSE_MOVE_DELAY 30

#endif // TURRET_CONFIG__TRAVERSE_CONFIG_H
