
#ifndef TURRET_CONFIG__TRAVERSE_CONFIG_H
#define TURRET_CONFIG__TRAVERSE_CONFIG_H

#define TRAVERSE_LIMIT_MIN 40
#define TRAVERSE_LIMIT_MAX 140
#define TRAVERSE_LIMIT_STRAIGHT 90

#define TRAVERSE_MOVE_DELAY 10

#endif // TURRET_CONFIG__TRAVERSE_CONFIG_H
