
#ifndef TURRET_CONFIG__TRAVERSE_CONFIG_H
#define TURRET_CONFIG__TRAVERSE_CONFIG_H

#define TRAVERSE_LIMIT_MIN 10
#define TRAVERSE_LIMIT_MIN_INTRADS 175
#define TRAVERSE_LIMIT_MAX 170
#define TRAVERSE_LIMIT_MAX_INTRADS 2967
#define TRAVERSE_LIMIT_STRAIGHT 90
#define TRAVERSE_LIMIT_STRAIGHT_INTRADS 1570

#define FUNCTION_CHECK_TGT_INTRADS_1 700
#define FUNCTION_CHECK_TGT_INTRADS_2 2200

#define TRAVERSE_MOVE_DELAY 30
#define TRAVERSE_MOVE_DELAY_SLOW 60

#endif // TURRET_CONFIG__TRAVERSE_CONFIG_H
