//
// Created by graham on 10/6/18.
//

#ifndef TURRETCONFIG_TURRETCONFIGPLACARD_H
#define TURRETCONFIG_TURRETCONFIGPLACARD_H


class TurretConfigPlacard {

};


#endif //TURRETCONTROLLERS_TURRETCONFIGPLACARD_H
