.PHONY: clean All

All:
	@echo "----------Building project:[ arduinoLibraries - Debug ]----------"
	@"$(MAKE)" -f  "arduinoLibraries.mk"
clean:
	@echo "----------Cleaning project:[ arduinoLibraries - Debug ]----------"
	@"$(MAKE)" -f  "arduinoLibraries.mk" clean
