.PHONY: clean All

All:
	@echo "----------Building project:[ ardSketches - Debug ]----------"
	@"$(MAKE)" -f  "ardSketches.mk"
clean:
	@echo "----------Cleaning project:[ ardSketches - Debug ]----------"
	@"$(MAKE)" -f  "ardSketches.mk" clean
